<?php

namespace Database\Seeders;

use App\Models\Program;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class ProgramsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $admin = User::where('email', 'admin@kfa.kg')->first();

        if (!$admin) {
            $this->command->error('Admin user not found. Please create admin user first.');
            return;
        }

        $programs = [
            [
                'title' => 'Профессиональный курс по МСФО',
                'slug' => 'professionalnyj-kurs-po-msfo',
                'description' => 'Комплексная программа обучения Международным стандартам финансовой отчетности (МСФО). Подходит для бухгалтеров, финансовых специалистов и аудиторов. Включает теоретические занятия и практические кейсы.',
                'program_type' => 'course',
                'status' => 'enrollment_open',
                'duration' => '3 месяца',
                'cpe_hours' => 48.0,
                'language' => 'ru',
                'level' => 'intermediate',
                'instructor_name' => 'Айгуль Токтобаева',
                'instructor_bio' => 'Сертифицированный финансовый аналитик (CFA), эксперт по МСФО с 15-летним опытом.',
                'syllabus' => "Модуль 1: Введение в МСФО\nМодуль 2: Концептуальные основы\nМодуль 3: Представление финансовой отчетности\nМодуль 4: Учет основных средств и нематериальных активов\nМодуль 5: Финансовые инструменты\nМодуль 6: Консолидация и МСФО 10\nМодуль 7: Учет доходов по МСФО 15\nМодуль 8: Практические кейсы и экзамен",
                'prerequisites' => 'Базовые знания бухгалтерского учета',
                'target_audience' => 'Бухгалтеры, финансовые специалисты, аудиторы, студенты финансовых специальностей',
                'starts_at' => Carbon::now()->addDays(20),
                'ends_at' => Carbon::now()->addDays(110),
                'schedule' => 'Вторник и Четверг, 18:00-21:00',
                'max_students' => 30,
                'enrolled_count' => 0,
                'enrollment_deadline' => Carbon::now()->addDays(15),
                'requires_approval' => true,
                'price' => 25000.00,
                'member_price' => 20000.00,
                'is_online' => true,
                'platform' => 'Zoom + LMS система',
                'modules' => [
                    ['number' => 1, 'title' => 'Введение в МСФО', 'duration' => '6 часов'],
                    ['number' => 2, 'title' => 'Концептуальные основы', 'duration' => '6 часов'],
                    ['number' => 3, 'title' => 'Представление отчетности', 'duration' => '6 часов'],
                    ['number' => 4, 'title' => 'Основные средства', 'duration' => '6 часов'],
                    ['number' => 5, 'title' => 'Финансовые инструменты', 'duration' => '6 часов'],
                    ['number' => 6, 'title' => 'Консолидация', 'duration' => '6 часов'],
                    ['number' => 7, 'title' => 'Учет доходов', 'duration' => '6 часов'],
                    ['number' => 8, 'title' => 'Практика и экзамен', 'duration' => '6 часов'],
                ],
                'has_exam' => true,
                'passing_score' => 70,
                'issues_certificate' => true,
                'image' => '/images/programs/msfo-course.jpg',
                'is_featured' => true,
                'published_at' => Carbon::now(),
                'created_by' => $admin->id,
            ],
            [
                'title' => 'Финансовый анализ и моделирование',
                'slug' => 'finansovyj-analiz-i-modelirovanie',
                'description' => 'Практический курс по финансовому анализу и построению финансовых моделей. Научитесь анализировать финансовую отчетность, строить прогнозы и оценивать бизнес.',
                'program_type' => 'course',
                'status' => 'enrollment_open',
                'duration' => '6 недель',
                'cpe_hours' => 24.0,
                'language' => 'ru',
                'level' => 'intermediate',
                'instructor_name' => 'Азамат Султанов',
                'instructor_bio' => 'Инвестиционный аналитик, CFA Level 2, опыт в венчурных фондах и M&A.',
                'syllabus' => "Неделя 1: Основы финансового анализа\nНеделя 2: Анализ финансовой отчетности\nНеделя 3: Коэффициентный анализ\nНеделя 4: Построение финансовых моделей в Excel\nНеделя 5: Оценка бизнеса (DCF, мультипликаторы)\nНеделя 6: Проектная работа",
                'prerequisites' => 'Уверенное владение Excel, базовые знания финансов',
                'target_audience' => 'Финансовые аналитики, инвесторы, менеджеры',
                'starts_at' => Carbon::now()->addDays(14),
                'ends_at' => Carbon::now()->addDays(56),
                'schedule' => 'Среда и Пятница, 19:00-21:00',
                'max_students' => 25,
                'enrolled_count' => 0,
                'enrollment_deadline' => Carbon::now()->addDays(10),
                'requires_approval' => false,
                'price' => 18000.00,
                'member_price' => 15000.00,
                'is_online' => true,
                'platform' => 'Zoom',
                'modules' => [
                    ['number' => 1, 'title' => 'Основы финансового анализа', 'duration' => '4 часа'],
                    ['number' => 2, 'title' => 'Анализ отчетности', 'duration' => '4 часа'],
                    ['number' => 3, 'title' => 'Коэффициентный анализ', 'duration' => '4 часа'],
                    ['number' => 4, 'title' => 'Финансовое моделирование', 'duration' => '4 часа'],
                    ['number' => 5, 'title' => 'Оценка бизнеса', 'duration' => '4 часа'],
                    ['number' => 6, 'title' => 'Проектная работа', 'duration' => '4 часа'],
                ],
                'has_exam' => true,
                'passing_score' => 65,
                'issues_certificate' => true,
                'image' => '/images/programs/financial-analysis.jpg',
                'is_featured' => true,
                'published_at' => Carbon::now(),
                'created_by' => $admin->id,
            ],
            [
                'title' => 'Подготовка к сертификации CFA Level 1',
                'slug' => 'podgotovka-k-sertifikacii-cfa-level-1',
                'description' => 'Интенсивный курс подготовки к экзамену CFA Level 1. Покрывает все темы программы CFA: этика, количественные методы, экономика, финансовая отчетность, корпоративные финансы, инвестиции.',
                'program_type' => 'certification_prep',
                'status' => 'enrollment_open',
                'duration' => '4 месяца',
                'cpe_hours' => 80.0,
                'language' => 'ru/en',
                'level' => 'advanced',
                'instructor_name' => 'Команда инструкторов CFA',
                'instructor_bio' => 'Сертифицированные CFA чартерхолдеры с опытом подготовки кандидатов.',
                'syllabus' => "1. Ethics & Professional Standards\n2. Quantitative Methods\n3. Economics\n4. Financial Reporting & Analysis\n5. Corporate Finance\n6. Equity Investments\n7. Fixed Income\n8. Derivatives\n9. Alternative Investments\n10. Portfolio Management\n11. Mock Exams & Review",
                'prerequisites' => 'Высшее образование, свободное владение английским языком',
                'target_audience' => 'Кандидаты на сертификацию CFA',
                'starts_at' => Carbon::now()->addDays(30),
                'ends_at' => Carbon::now()->addDays(150),
                'schedule' => 'Суббота, 10:00-16:00',
                'max_students' => 20,
                'enrolled_count' => 0,
                'enrollment_deadline' => Carbon::now()->addDays(25),
                'requires_approval' => true,
                'price' => 45000.00,
                'member_price' => 38000.00,
                'is_online' => false,
                'location' => 'Бишкек, учебный центр КФА',
                'modules' => [
                    ['number' => 1, 'title' => 'Ethics & Professional Standards', 'duration' => '8 часов'],
                    ['number' => 2, 'title' => 'Quantitative Methods', 'duration' => '8 часов'],
                    ['number' => 3, 'title' => 'Economics', 'duration' => '8 часов'],
                    ['number' => 4, 'title' => 'Financial Reporting', 'duration' => '10 часов'],
                    ['number' => 5, 'title' => 'Corporate Finance', 'duration' => '8 часов'],
                    ['number' => 6, 'title' => 'Equity Investments', 'duration' => '8 часов'],
                    ['number' => 7, 'title' => 'Fixed Income', 'duration' => '8 часов'],
                    ['number' => 8, 'title' => 'Derivatives', 'duration' => '6 часов'],
                    ['number' => 9, 'title' => 'Alternative Investments', 'duration' => '6 часов'],
                    ['number' => 10, 'title' => 'Portfolio Management', 'duration' => '6 часов'],
                    ['number' => 11, 'title' => 'Mock Exams', 'duration' => '4 часа'],
                ],
                'has_exam' => true,
                'passing_score' => 70,
                'issues_certificate' => true,
                'image' => '/images/programs/cfa-prep.jpg',
                'is_featured' => true,
                'published_at' => Carbon::now(),
                'created_by' => $admin->id,
            ],
            [
                'title' => 'Excel для финансистов: продвинутый уровень',
                'slug' => 'excel-dlya-finansistov-prodvinutyj-uroven',
                'description' => 'Продвинутый курс по работе с Excel для финансовых специалистов. Сводные таблицы, Power Query, Power Pivot, макросы VBA, автоматизация отчетности.',
                'program_type' => 'online_course',
                'status' => 'enrollment_open',
                'duration' => '4 недели',
                'cpe_hours' => 16.0,
                'language' => 'ru',
                'level' => 'intermediate',
                'instructor_name' => 'Олег Петров',
                'instructor_bio' => 'Excel MVP, тренер по финансовому моделированию, 10+ лет опыта.',
                'syllabus' => "Неделя 1: Продвинутые формулы и функции\nНеделя 2: Сводные таблицы и визуализация\nНеделя 3: Power Query и Power Pivot\nНеделя 4: VBA макросы и автоматизация",
                'prerequisites' => 'Базовые навыки работы с Excel',
                'target_audience' => 'Финансовые аналитики, бухгалтеры, контроллеры',
                'starts_at' => Carbon::now()->addDays(10),
                'ends_at' => Carbon::now()->addDays(38),
                'schedule' => 'Самостоятельное обучение + вебинары по Понедельникам 19:00',
                'max_students' => 50,
                'enrolled_count' => 0,
                'enrollment_deadline' => Carbon::now()->addDays(8),
                'requires_approval' => false,
                'price' => 8000.00,
                'member_price' => 6000.00,
                'is_online' => true,
                'platform' => 'LMS + Zoom вебинары',
                'modules' => [
                    ['number' => 1, 'title' => 'Продвинутые формулы', 'duration' => '4 часа'],
                    ['number' => 2, 'title' => 'Сводные таблицы', 'duration' => '4 часа'],
                    ['number' => 3, 'title' => 'Power Query & Pivot', 'duration' => '4 часа'],
                    ['number' => 4, 'title' => 'VBA макросы', 'duration' => '4 часа'],
                ],
                'has_exam' => false,
                'passing_score' => null,
                'issues_certificate' => true,
                'image' => '/images/programs/excel-advanced.jpg',
                'is_featured' => false,
                'published_at' => Carbon::now(),
                'created_by' => $admin->id,
            ],
            [
                'title' => 'Управленческий учет и бюджетирование',
                'slug' => 'upravlencheskij-uchet-i-byudzhetirovanie',
                'description' => 'Курс по управленческому учету и системам бюджетирования. Научитесь строить эффективную систему управленческого учета, планировать бюджеты и контролировать исполнение.',
                'program_type' => 'course',
                'status' => 'published',
                'duration' => '8 недель',
                'cpe_hours' => 32.0,
                'language' => 'ru',
                'level' => 'intermediate',
                'instructor_name' => 'Марина Иванова',
                'instructor_bio' => 'Финансовый директор, эксперт по управленческому учету, CIMA.',
                'syllabus' => "Модуль 1: Основы управленческого учета\nМодуль 2: Центры финансовой ответственности\nМодуль 3: Калькулирование себестоимости\nМодуль 4: Бюджетирование: основы\nМодуль 5: Операционное бюджетирование\nМодуль 6: Финансовое бюджетирование\nМодуль 7: Контроль и анализ исполнения\nМодуль 8: Управленческая отчетность",
                'prerequisites' => 'Знание основ бухгалтерского учета',
                'target_audience' => 'Финансовые менеджеры, контроллеры, CFO',
                'starts_at' => Carbon::now()->addDays(35),
                'ends_at' => Carbon::now()->addDays(91),
                'schedule' => 'Вторник и Четверг, 18:30-20:30',
                'max_students' => 30,
                'enrolled_count' => 0,
                'enrollment_deadline' => Carbon::now()->addDays(30),
                'requires_approval' => false,
                'price' => 22000.00,
                'member_price' => 18000.00,
                'is_online' => true,
                'platform' => 'Zoom',
                'modules' => [
                    ['number' => 1, 'title' => 'Основы управленческого учета', 'duration' => '4 часа'],
                    ['number' => 2, 'title' => 'ЦФО', 'duration' => '4 часа'],
                    ['number' => 3, 'title' => 'Калькулирование', 'duration' => '4 часа'],
                    ['number' => 4, 'title' => 'Бюджетирование: основы', 'duration' => '4 часа'],
                    ['number' => 5, 'title' => 'Операционный бюджет', 'duration' => '4 часа'],
                    ['number' => 6, 'title' => 'Финансовый бюджет', 'duration' => '4 часа'],
                    ['number' => 7, 'title' => 'Контроль исполнения', 'duration' => '4 часа'],
                    ['number' => 8, 'title' => 'Управленческая отчетность', 'duration' => '4 часа'],
                ],
                'has_exam' => true,
                'passing_score' => 70,
                'issues_certificate' => true,
                'image' => '/images/programs/management-accounting.jpg',
                'is_featured' => false,
                'published_at' => Carbon::now(),
                'created_by' => $admin->id,
            ],
        ];

        foreach ($programs as $programData) {
            Program::create($programData);
        }

        $this->command->info('Programs seeded successfully! Created ' . count($programs) . ' programs.');
    }
}
